version: '3.6'

services:
    hugo:
        image: "monachus/hugo:v0.62.0"
        container_name: hugo
        restart: unless-stopped
        hostname: hugo
        ports:
            - "1313:1313"
        volumes:
            - $PWD/data:/usr/share/blog:rw
        environment:
          - HUGO_BASE_URL==${HUGO_BASE_URL}
        command: hugo server -b=${HUGO_BASE_URL} --bind=0.0.0.0 -p 1313 --appendPort=false --watch=false --liveReloadPort=1313
        