version: '3.6'

services:
    coredns:
        image: "coredns/coredns:1.6.6"
        container_name: coredns
        restart: unless-stopped
        hostname: coredns
        # ports:
        #     - "53:53"
        #     - "53:53/udp"
        network_mode: host
        volumes:
            - /etc/resolv.conf:/etc/resolv.conf:ro
            - $PWD/data:/etc/coredns:rw
        command: -conf /etc/coredns/Corefile
