version: '3.6'

services:
    nginx:
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        image: "recallsong/nginx-acme:1.17.6-alpine"
        container_name: nginx
        restart: unless-stopped
        hostname: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - $PWD/data/html:/usr/share/nginx/html:rw
            - $PWD/data/conf:/etc/nginx/conf.d:rw
            - $PWD/data/logs:/var/log/nginx:rw
            - $PWD/data/acme.sh/${DOMAIN}:/root/.acme.sh/${DOMAIN}:rw
        environment:
          - DOMAIN=${DOMAIN}
          - ACME_CMD="${ACME_CMD}"
          - Ali_Key=${Ali_Key}
          - Ali_Secret=${Ali_Secret}
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536