version: '3.6'

services:
    nginx:
        image: "nginx:1.17.6-alpine"
        container_name: nginx
        restart: unless-stopped
        hostname: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - $PWD/data/html:/usr/share/nginx/html:rw
            - $PWD/data/conf/conf.d:/etc/nginx/conf.d:rw
            - $PWD/data/logs:/var/log/nginx:rw
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536