version: '3.6'

services:
    mysql:
        image: "mysql:5.7.22"
        container_name: mysql
        hostname: mysql
        restart: always
        ports:
          - "3306:3306"
        volumes:
          - $PWD/data:/var/lib/mysql:rw
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci