version: '3.6'

services:
    redis:
        image: "redis:4.0-alpine"
        container_name: redis
        restart: unless-stopped
        hostname: redis
        ports:
            - "6379:6379"
        volumes:
            - $PWD/data:/data:rw